[package]
name = "time-tracker-gui"
version = "0.1.0"
edition = "2021"
authors = ["Tobias Schaffner <tobiasschaffner87@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.15.3"
rand = "*"
